
#LAYOUT
DIMENSIONS = 4
PADDING_ELEMENTS = 10
PADDING_GAME_BOARD = 50
MAIN_BOARD_CELL_SIZE = 50
MAIN_BOARD_ORIGIN = (PADDING_GAME_BOARD, PADDING_GAME_BOARD)
PLAYER_BOARD_CELL_SIZE = 80
BORDER_WIDTH = 3
CARD_WIDTH = 40
CARD_BORDER_WIDTH = 1
CARD_DIMENSIONS = 2
BUTTON_HEIGHT = CARD_WIDTH * 2
BUTTON_WIDTH = 200
ACTION_BUTTON_ORIGIN_X = DIMENSIONS * MAIN_BOARD_CELL_SIZE + MAIN_BOARD_ORIGIN[0] + PADDING_ELEMENTS
PLAYER_BOARD_ORIGIN = (ACTION_BUTTON_ORIGIN_X + BUTTON_WIDTH + PADDING_ELEMENTS, PADDING_GAME_BOARD)
GAME_BOARD_WIDTH = PLAYER_BOARD_ORIGIN[0] + DIMENSIONS * CARD_DIMENSIONS * CARD_WIDTH + PADDING_GAME_BOARD
GAME_BOARD_HEIGHT = PADDING_GAME_BOARD * 2 + DIMENSIONS * CARD_WIDTH * CARD_DIMENSIONS

print(PLAYER_BOARD_ORIGIN, GAME_BOARD_WIDTH, GAME_BOARD_HEIGHT)

#COLORS
BACKGROUND_COLOR = (30, 30, 30)
EMPTY_CELL_COLOR = (100, 100, 100)
HIGHLIGHT_COLOR = (255, 0, 255)
OUTLINE_COLOR = (0, 0, 0)
BUTTON_COLOR = (200, 200, 200)
TEXT_COLOR = (0, 0, 0)

#FONT
FONT_SIZE = 36